### PR TITLE
low-level interface

### PR DESCRIPTION
**Pull request by bo3mrh**
This is the first pull request to start switch ACHP to low-level interface

### CODE REVIEW

**Comment by bo3mrh** [comment]
Hello @ibell,
Could you please look over this PR. I want to make sure I got the low-level right for the compressor model before I continue working on the other models.

**Comment by ibell** [comment]
You've got the right idea - can you please delete the calls to PropsSI that you are replacing though?  It would also be great if we could add some tests to the code as we convert them to use the low-level interface to make sure it is all still working properly.

**Comment by ibell** [comment]
Another thing is I like it if at every line where you have a parameter with units, if you write the units to the right of the line, it makes it easier to see the units at a glance.

**Comment by bo3mrh** [comment]
Before I PR, I tested the code if it generates the same results.

**Comment by bo3mrh** [comment]
better ?

**Comment by bo3mrh** [comment]
Hey @ibell 
I tested all files including component and cycle models. Everything is working fine.
In cycle mode, it is about 3x faster than before.
Would you like to check before PR? or I can go ahead and pull it ?

**Comment by ibell** [comment]
Awesome!  I'm glad to hear that it is already 3 times faster when you use the low-level interface.  Here are a few more ideas that could make it even faster I think:
1. Convert the Correlations.py to use the low-level interface if you haven't already (more important because there are PQ flashes in there)
2. Pass AbstractState instances between classes, rather than making new ones for each class (probably less important)
3. Using tabular backends inplace of HEOS backend.

**Comment by ibell** [comment]
Sorry, scratch that, you already converted them.  Anyway, good work, and I'll merge this PR.

**Comment by bo3mrh** [comment]
In Correlations.py, what do you think if I used: 
```
h_l = AS.saturated_liquid_keyed_output(CP.iHmass)
h_v = AS.saturated_vapor_keyed_output(CP.iHmass)
```
instead of
```
AS.update(CP.QT_INPUTS,0.0,Tbubble)
h_l =AS.hmass()
AS.update(CP.QT_INPUTS,1.0,Tdew)
h_v=AS.hmass()
```
I guess this make it a bit faster ?

**Comment by ibell** [comment]
Yes, the only problem is that for pseudo-pure fluids (like R410A) or
mixtures, this isn't exactly what you want, and the old way is probably
better.  For basically azeotropic mixtures it doesn't matter, but as the
glide increases it becomes more important to think this through.

**Comment by bo3mrh** [comment]
Then, I will keep as it is. Thanks

**Pull request merged**
