### PR TITLE
clean up and update documentation files

### PR DESCRIPTION
**Pull request by bo3mrh**
update documentation files with low-level interface
major clean up for all files
ignore all commits, but check out the last two commits only.

### CODE REVIEW

**Comment by ibell** [comment]
Thanks! Can you rebase your changes onto master though?  There are a lot of spurious commits from your last PR.  I think @davideziviani might be able to help you with that.

**Comment by ibell** [comment]
I squash/merged your commits.  Can you in the future rebase your master onto ACHP's master and do all your work in a branch on your fork?  That way there will no longer be spurious commits.

**Comment by bo3mrh** [comment]
I am so sorry for that.
I didn't notice this until I PR. Certainly, I will avoid this in future.

**Comment by ibell** [comment]
No problem, takes a few tries with git to make sense of all the bits and
pieces.  I'll give you push ability at some point, but I'd like to review
your changes for now.

**Comment by davideziviani** [comment]
Sure! Also @ibell , from January I will be start working on ACHP in one of my projects at Herrick. I talked already to Ammar and we will create a todo list.

**Pull request merged**
